In [1]:
import numpy as np

In [66]:
# 1. Create a 3x3 array filled with random integers between 0 and 10.  Calculate the sum, mean, and standard deviation of the array.
arr=np.random.randint(0, 11, (3, 3))
sum_val = np.sum(arr)
mean_val = np.mean(arr)
std_val = np.std(arr)
arr,sum_val,mean_val,std_val

(array([[9, 4, 8],
        [3, 1, 1],
        [0, 5, 0]], dtype=int32),
 np.int64(31),
 np.float64(3.4444444444444446),
 np.float64(3.1661792997277796))

In [67]:
# 2. Create a 1D array of 10 elements and compute the cumulative sum of the elements.
arr1=np.random.randint(0, 11, 10)
cumsum_array = np.cumsum(arr1)
arr1,cumsum_array

(array([10,  9, 10, 10,  8, 10,  7,  5,  3,  5], dtype=int32),
 array([10, 19, 29, 39, 47, 57, 64, 69, 72, 77]))

In [68]:
# 3. Generate two 2x3 arrays with random integers and perform element-wise addition, subtraction, multiplication, and division.
arr2=np.random.randint(1, 11, (2, 3))
arr3=np.random.randint(1, 11, (2, 3))
add_result = arr2 + arr3
sub_result = arr2 - arr3
mul_result = arr2 * arr3
div_result = arr2 / arr3
arr2,arr3,add_result,sub_result,mul_result,div_result

(array([[ 8,  9,  4],
        [ 9,  8, 10]], dtype=int32),
 array([[9, 6, 4],
        [9, 1, 5]], dtype=int32),
 array([[17, 15,  8],
        [18,  9, 15]], dtype=int32),
 array([[-1,  3,  0],
        [ 0,  7,  5]], dtype=int32),
 array([[72, 54, 16],
        [81,  8, 50]], dtype=int32),
 array([[0.88888889, 1.5       , 1.        ],
        [1.        , 8.        , 2.        ]]))

In [69]:
# 4. Create a 4x4 identity matrix.
identity_matrix = np.eye(4)  
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [70]:
# 5. Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.
a = np.array([5, 10, 15, 20, 25])
div= a/5
div

array([1., 2., 3., 4., 5.])

In [71]:
# 6. Reshape a 1D array of 12 elements into a 3x4 matrix.
array_reshape = np.arange(12).reshape(3, 4)
array_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
# 7. Flatten a 3x3 matrix into a 1D array.
flattened_array = arr.flatten()
arr,flattened_array

(array([[9, 4, 8],
        [3, 1, 1],
        [0, 5, 0]], dtype=int32),
 array([9, 4, 8, 3, 1, 1, 0, 5, 0], dtype=int32))

In [73]:
# 8. Stack two 3x3 matrices horizontally and vertically.
matrix_a = np.random.randint(0, 11, (3, 3))
matrix_b = np.random.randint(0, 11, (3, 3))
h_stack = np.hstack((matrix_a, matrix_b))
v_stack = np.vstack((matrix_a, matrix_b))
h_stack,v_stack

(array([[ 9,  3,  4,  4, 10,  6],
        [ 8,  6, 10,  7,  9,  9],
        [ 0,  7, 10,  0,  9,  1]], dtype=int32),
 array([[ 9,  3,  4],
        [ 8,  6, 10],
        [ 0,  7, 10],
        [ 4, 10,  6],
        [ 7,  9,  9],
        [ 0,  9,  1]], dtype=int32))

In [74]:
# 9. Concatenate two arrays of different sizes along a new axis
array_1 = np.random.randint(0, 11, (3,))
array_2 = np.random.randint(0, 11, (5,))
concat_axis = np.array([array_1, array_2], dtype=object)
concat_axis

array([array([ 2, 10,  3], dtype=int32),
       array([7, 7, 0, 3, 5], dtype=int32)], dtype=object)

In [75]:
# 10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.
matrix_3x2 = np.random.randint(0, 11, (3, 2))
transposed_matrix = matrix_3x2.T
reshaped_matrix = transposed_matrix.reshape(3, 2)
transposed_matrix,reshaped_matrix

(array([[4, 2, 4],
        [4, 0, 1]], dtype=int32),
 array([[4, 2],
        [4, 4],
        [0, 1]], dtype=int32))

In [76]:
# 11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.
array = np.arange(15)
sliced_array = array[2:10:2]
sliced_array

array([2, 4, 6, 8])

In [77]:
# 12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and columns 2 to 4.
matrix = np.random.randint(0, 11, (5, 5))
sub_matrix = matrix[1:4,2:5]
matrix,sub_matrix

(array([[ 5,  9,  4,  9,  4],
        [10,  9,  2,  8,  3],
        [ 3,  7,  3, 10,  9],
        [ 4,  4,  8,  8,  1],
        [ 9,  7, 10,  0,  7]], dtype=int32),
 array([[ 2,  8,  3],
        [ 3, 10,  9],
        [ 8,  8,  1]], dtype=int32))

In [78]:
# 13. Replace all elements in a 1D array greater than 10 with the value 10.array_replaced = np.random.randint(0, 20, 10)
array_replaced[array_replaced > 10] = 10
array_replaced

array([ 2, 10,  4,  7,  7,  4, 10, 10, 10, 10], dtype=int32)

In [79]:
# 14. Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].
array_fancy = np.arange(10)
fancy_selected = array_fancy[[0, 2, 4, 6]]
fancy_selected

array([0, 2, 4, 6])

In [80]:
# 15. Create a 1D array of 10 elements and reverse it using slicing.
reversed_array = np.arange(10)[::-1]
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [81]:
# 16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.
mat3 = np.random.randint(0, 11, (3, 3))
arr_3 = np.random.randint(0, 11, (1, 3))
broadcast_add = mat3 + arr_3
broadcast_add

array([[14, 14, 10],
       [ 6, 10, 15],
       [ 8, 14, 18]], dtype=int32)

In [82]:
# 17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.
array_scalar = np.arange(5) * 2
array_scalar

array([0, 2, 4, 6, 8])

In [83]:
# 18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.
mat4 = np.random.randint(0, 11, (3, 3))
arr_4 = np.random.randint(0, 11, (3, 1))
broadcast_sub = mat4 - arr_4
broadcast_sub

array([[-3, -7, -2],
       [ 0, -1,  9],
       [-6, -1, -4]], dtype=int32)

In [84]:
# 19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.
array_3d = np.random.randint(0, 11, (2, 3, 4))
scalar_added = array_3d + 5
scalar_added

array([[[ 6,  5, 15, 15],
        [10, 14, 14,  6],
        [ 8, 10,  9, 15]],

       [[15, 14, 13, 12],
        [13, 12, 11, 12],
        [13, 12,  7, 14]]], dtype=int32)

In [85]:
# 20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.
array5 = np.random.randint(0, 11, (4, 1))
array6 = np.random.randint(0, 11, (1, 5))
broadcast_sum = array5 + array6
broadcast_sum

array([[14,  9, 10, 15,  7],
       [18, 13, 14, 19, 11],
       [17, 12, 13, 18, 10],
       [17, 12, 13, 18, 10]], dtype=int32)

In [86]:
# 21. Compute the square root of each element in a 2D array using vectorized operations.
array_sqrt = np.random.randint(0, 11, (3, 3))
sqrt_array = np.sqrt(array_sqrt)
sqrt_array

array([[2.23606798, 3.        , 3.16227766],
       [2.44948974, 1.73205081, 2.44948974],
       [2.44948974, 2.64575131, 2.82842712]])

In [87]:
# 22. Calculate the dot product of two 1D arrays of size 5.
array_dot_a = np.random.randint(0, 11, 5)
array_dot_b = np.random.randint(0, 11, 5)
dot_product = np.dot(array_dot_a, array_dot_b)
dot_product

np.int32(107)

In [88]:
# 23. Perform element-wise comparison of two 1D arrays and return an array of boolean values indicating where the first array has larger elements.
array_a = np.random.randint(0, 11, 5)
array_b = np.random.randint(0, 11, 5)
result = array_a > array_b
array_a,array_b,result

(array([10,  5,  2,  0,  2], dtype=int32),
 array([10,  5,  6,  0,  8], dtype=int32),
 array([False, False, False, False, False]))

In [89]:
# 24. Create a 2D array and apply a vectorized operation to double the value of each element.
array_double = np.random.randint(0, 11, (3, 3)) 
array_double*2

array([[ 6, 10,  8],
       [ 4, 12,  2],
       [12, 18, 14]], dtype=int32)

In [90]:
# 25. Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations.
array100 = np.random.randint(0, 100, 100)
sum_even = np.sum(array100[array100 % 2 == 0])
sum_even

np.int64(2368)

In [91]:
# 26. Create a 3x3 matrix and find its determinant.
matrix_det = np.random.randint(1, 10, (3, 3))
determinant = np.linalg.det(matrix_det)
determinant

np.float64(-246.00000000000014)

In [92]:
# 27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.
matrix_a=np.random.randint(1, 10, (2, 2))
inverse_matrix = np.linalg.inv(matrix_a)
identity_check = np.dot(matrix_a, inverse_matrix)
identity_check

array([[1.00000000e+00, 1.22124533e-15],
       [0.00000000e+00, 1.00000000e+00]])

In [93]:
# 28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
eigenvalues, eigenvectors

(array([ 9.72015325, -0.72015325]),
 array([[ 0.88559411, -0.84396375],
        [ 0.46445999,  0.53640022]]))

In [94]:
# 29. Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.
A = np.array([[2, 3], [4, 6]])
B = np.array([5, 10])
x, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)
x

array([0.76923077, 1.15384615])

In [95]:
# 30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original matrix using the SVD components.
matrix_svd = np.random.randint(1, 10, (3, 3))
U, S, Vt = np.linalg.svd(matrix_svd)
reconstructed_matrix = U @ np.diag(S) @ Vt
reconstructed_matrix

array([[7., 5., 7.],
       [1., 9., 9.],
       [5., 6., 8.]])